Ng 11 view register values
needsguidance/Semref pull request #15
Opened 2019-10-21 16:47 UTC by cfboy

2019-10-21 20:32 UTC, alejoreyes96 approved these changes

2019-10-21 20:36 UTC, noelvalentin approved these changes

2019-10-21 20:50 UTC, ChristianPerez34 requested changes

2019-10-21 20:50 UTC, ChristianPerez34 commented on GUI/window.py
> +        self.register = kwargs.pop('registers')
Remove this line

2019-10-21 20:50 UTC, ChristianPerez34 commented on GUI/window.py
> +        self.register = kwargs.pop('registers')
Remove this line

2019-10-21 20:50 UTC, ChristianPerez34 commented on GUI/window.py
> +        self.add_widget(RunWindow(app=self.app, micro_sim=self.micro_sim, registers=self.register))
Remove ‘registers’

2019-10-21 20:50 UTC, ChristianPerez34 commented on GUI/window.py
> +        self.add_widget(MainWindow(nav_drawer=self, app=self.app, micro_sim=self.micro_sim, registers=REGISTER))
Remove ‘registers’

2019-10-21 20:50 UTC, ChristianPerez34 commented on microprocessor_simulator.py
> +            print(f'{RAM[i]} {RAM[i + 1]}')
Remove print

2019-10-21 20:50 UTC, ChristianPerez34 commented on microprocessor_simulator.py
> +        REGISTER['sp'] = f'{0:02x}'
Should clear all registers. General purpose registers, program counter, etc

2019-10-22 00:03 UTC, cfboy commented on GUI/window.py
> +        self.register = kwargs.pop('registers')
Ok

2019-10-22 00:09 UTC, ChristianPerez34 commented on GUI/window.py
> +class register_table(RecycleView):
`class RegisterTable(RecycleView)`

2019-10-22 00:09 UTC, ChristianPerez34 commented on GUI/window.py
> +        # self.register = REGISTER
Remove comment

2019-10-22 00:12 UTC, ChristianPerez34 commented on microprocessor_simulator.py
> +        REGISTER['pc'] = f'{0:03x}'
```Python
for k, v in REGISTER.items():
    if k == 'pc' or k == 'sp':
        REGISTER[k] = f'{0:03x}'
    elif k == 'ir':
        REGISTER[k] =  f'{0:04x}'
    else:
        REGISTER[k] = f'{0:02x}'
```

2019-10-22 00:13 UTC, ChristianPerez34 requested changes
Minor changes needed

2019-10-22 00:14 UTC, ChristianPerez34 approved these changes

2019-10-22 00:14 UTC, merged