Ng 25 segment display
needsguidance/Semref pull request #26
Opened 2019-10-27 19:26 UTC by cfboy

Added Seven Segment Display. (NG-25)

2019-10-27 22:25 UTC, ChristianPerez34 commented on GUI/window.py
> +    def __init__(self, **kwargs):
Not being used aside of calling super class. Should remove

2019-10-27 22:31 UTC, ChristianPerez34 requested changes

2019-10-27 22:31 UTC, ChristianPerez34 commented on GUI/window.py
> +        print(binary)
Print statement not needed

2019-10-27 22:31 UTC, ChristianPerez34 commented on GUI/window.py
> +        control_bit = int(binary[len(binary) - 1])
control_bit = int(binary[-1])

2019-10-27 22:31 UTC, ChristianPerez34 commented on GUI/window.py
> +                        print(bit)
Remove print

2019-10-27 22:31 UTC, ChristianPerez34 commented on GUI/window.py
> +    def __init__(self, **kwargs):
Not doing anything other than calling super class. Remove this method

2019-10-28 02:44 UTC, ChristianPerez34 approved these changes
You have an import that is not being used `secrets`.

2019-10-28 20:29 UTC, alejoreyes96 approved these changes

2019-10-28 22:59 UTC, noelvalentin approved these changes

2019-10-28 23:24 UTC, merged