Ng 42 visual indicators
needsguidance/Semref pull request #44
Opened 2019-11-07 21:37 UTC by cfboy

2019-11-09 00:13 UTC, alejoreyes96 approved these changes

2019-11-09 00:34 UTC, noelvalentin approved these changes

2019-11-09 01:14 UTC, ChristianPerez34 requested changes

2019-11-09 01:14 UTC, ChristianPerez34 commented on GUI/window.py
> +        self.loaded_file = MDIconButton(icon='file-check',
disable buttons so that they are not clickable. This is to avoid confusing the user

2019-11-11 02:06 UTC, ChristianPerez34 approved these changes

2019-11-11 02:07 UTC, merged