Ng 49 cleanup optimization
needsguidance/Semref pull request #59
Opened 2019-11-14 20:36 UTC by cfboy

2019-11-14 20:55 UTC, ChristianPerez34 requested changes
Pull from master. Will comment further recommendations once branch is up-to-date

2019-11-14 20:55 UTC, ChristianPerez34 commented on GUI/semref.kv
> +            rgb: self.border
`rgb: self.border_color`

2019-11-14 20:55 UTC, ChristianPerez34 commented on GUI/semref.kv
> +            rgb: self.border
`rgb: self.border_color`

2019-11-14 20:55 UTC, ChristianPerez34 commented on GUI/window.py
> +theme_manager = ThemeManager()
Can be accessed from from application. Should not be a global variable

2019-11-14 20:55 UTC, ChristianPerez34 commented on GUI/window.py
> +    global theme_manager
Can be accessed from app. Not needed

2019-11-14 20:55 UTC, ChristianPerez34 commented on GUI/window.py
> +    border = ListProperty(theme_manager.primary_color)
should be inside `__init__`

2019-11-14 20:55 UTC, ChristianPerez34 commented on GUI/window.py
> +    global theme_manager
Can be accessed from app. Not needed

2019-11-14 20:55 UTC, ChristianPerez34 commented on GUI/window.py
> +    border = ListProperty(theme_manager.primary_color)
theme manager can be accessed from app. You might need to move this inside of the `__init__` method

`border_color = ListProperty(theme_manager.primary_color)`

2019-11-14 20:55 UTC, ChristianPerez34 commented on utils.py
> +    Converts int number to hexadecimal
Converts number to its binary representation

2019-11-14 20:55 UTC, ChristianPerez34 commented on utils.py
> +    :return: str:
:param num: int
      :param bits: str
      :return: str

2019-11-14 20:55 UTC, ChristianPerez34 commented on utils.py
> +# This ports are reserved by a I/O devices.
Reserved ports for I/O devices.

2019-11-15 00:07 UTC, ChristianPerez34 requested changes
Doesn't conform to upper case naming style
```Python
file_path = ''
can_write = False
loaded_file = False
run_editor = True
editor_saved = False
cleared = True
is_obj = False
```
`HexKeyboard`
simplify if statements

```Python
            for i in range(16):
                if i < 4:
                    Line(rectangle=(dp(340 + (89 * (i % 4))),
                                    dp(357), dp(87), dp(35)), width=dp(0.8))
                elif i >= 4 and i < 8:
                    Line(rectangle=(dp(340 + (89 * (i % 4))),
                                    dp(322), dp(87), dp(35)), width=dp(0.8))
                elif i >= 8 and i < 12:
                    Line(rectangle=(dp(340 + (89 * (i % 4))),
                                    dp(287), dp(87), dp(35)), width=dp(0.8))
                else:
                    Line(rectangle=(dp(340 + (89 * (i % 4))),
                                    dp(252), dp(87), dp(35)), width=dp(0.8))
```

`def write_ram(self)`, `def check_loader(self, dt)`, `def open_keyboard(self, instance)`, `def update_io(self, dt)`, `def run_micro_instructions(self, instance)`, `def run_micro_instructions_step(self, instance)`, `def assembler(self)`, `def run_micro_sim(self, file)` missing docstring

`def run_micro_instructions` edit for loop to a while loop since m is not being used
```Python
                for m in range(2):
                    if self.first_inst:
                        self.run_window.inst_table.data_list.clear()
                        self.run_window.inst_table.get_data(self.micro_sim.index,
                                                            self.micro_sim.disassembled_instruction())
                        self.run_window.inst_table.get_data(self.micro_sim.index,
                                                            self.micro_sim.disassembled_instruction())
                        self.first_inst = False
                    else:
                        self.micro_sim.prev_index = -1
                        self.run_window.blinking_on.cancel()
                        self.run_window.blinking_off.cancel()

                        self.run_window.blinking_on()
                        self.run_window.blinking_off()

                        timeout = time.time() + 5  # 5 seconds from now
                        while self.micro_sim.is_running:
                            try:
                                self.micro_sim.run_micro_instructions(timeout)
                                self.run_window.inst_table.get_data(self.micro_sim.index,
                                                                    self.micro_sim.disassembled_instruction())

                                if self.micro_sim.prev_index == self.micro_sim.index:
                                    self.micro_sim.is_running = False
                                else:
                                    self.micro_sim.prev_index = self.micro_sim.index
                            except (SystemError, TimeoutError) as e:
                                self.micro_sim.is_running = False
                                toast_message = f'Error! {e}'
                    self.run_window.reg_table.get_data()
                    self.run_window.mem_table.data_list.clear()
                    self.run_window.mem_table.get_data()
                    toast(toast_message)
```

`def assembler(self)` m is not being used. Change for loop to a while loop
```Python
            for m in range(50):
                f.write(f'{RAM_ASSEMBLER[i]} {RAM_ASSEMBLER[i + 1]}' + '\n')
                i += 2
```

2019-11-15 00:07 UTC, ChristianPerez34 commented on GUI/window.py
> +from kivy.properties import ListProperty, get_color_from_hex
from kivy.utils import get_color_from_hex

Must also run the pycharm optimize imports feature

2019-11-15 00:07 UTC, ChristianPerez34 commented on utils.py
> +    :param is_ram_loaded:
:param instance: obj
:param is_ram_loaded: bool

2019-11-15 00:18 UTC, ChristianPerez34 commented
`def clear_dialog(self, instance)`, `def clear_decision(self, *args)`, `def clear(self)`, `def clear_run(self)`, `def open_editor_save_dialog(self, instance)`, `def save_asm_file(self, *args)`, `def buttons_information(self, instance)`, `def io_config_open(self, instance)`, `def save_io_ports(self, *args)`, `def file_manager_open(self, instance)`, `def get_data(self)` missing docstring

`def save_file` m is not used. Change for loop to a while loop
```Python
            for m in range(50):
                f.write(f'\n{RAM[i]}    {RAM[i + 1]}')
                i += 2
```

2019-11-15 22:48 UTC, noelvalentin approved these changes

2019-11-16 15:12 UTC, ChristianPerez34 approved these changes

2019-11-16 15:22 UTC, merged