Ng 14 assembler bug fix
needsguidance/Semref pull request #9
Opened 2019-10-11 23:34 UTC by ChristianPerez34

Fixed bug with assembler. It should now produce the correct output files. Added tests to ensure proper functionality.

2019-10-12 01:46 UTC, cfboy approved these changes

2019-10-12 01:47 UTC, noelvalentin approved these changes

2019-10-12 02:09 UTC, cfboy requested changes

2019-10-12 02:09 UTC, cfboy commented on assembler.py
> -    def convert_all_to_binary(self):
Eliminaste el convert_all_to_binary pero se sigue llamando desde el main.py.

2019-10-12 02:17 UTC, ChristianPerez34 commented on assembler.py
> -    def convert_all_to_binary(self):
Removed call from main

2019-10-15 03:51 UTC, cfboy approved these changes

2019-10-15 03:52 UTC, alejoreyes96 approved these changes

2019-10-15 15:40 UTC, merged